#!/usr/bin/env python3
import os
import json
import sys
import requests
from datetime import datetime
from dotenv import load_dotenv

load_dotenv()

OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
GITHUB_TOKEN = os.getenv("GH_PAT") or os.getenv("GITHUB_TOKEN")
REPO = os.getenv("GITHUB_REPOSITORY", "atalanrafael-jpg/Ro-app")
ISSUE_LABELS = ["ai/draft"]

if not OPENAI_API_KEY:
    print("Missing OPENAI_API_KEY in env")
    sys.exit(1)
if not GITHUB_TOKEN:
    print("Missing GH_PAT or GITHUB_TOKEN in env")
    sys.exit(1)


def generate_variants(topic: str, count: int = 3):
    import openai

    openai.api_key = OPENAI_API_KEY
    prompt = f"Generate {count} distinct short social media post variations about: \"{topic}\". Each variant should be a single paragraph, 1-2 sentences. Provide results as a JSON array."
    resp = openai.ChatCompletion.create(
        model=os.getenv("OPENAI_MODEL", "gpt-4o-mini"),
        messages=[{"role": "user", "content": prompt}],
        temperature=0.8,
        max_tokens=400,
    )
    text = resp["choices"][0]["message"]["content"].strip()
    # Try to parse JSON from response; fallback to simple splitting
    try:
        arr = json.loads(text)
        if isinstance(arr, list):
            return arr[:count]
    except Exception:
        # fallback: split on lines
        lines = [l.strip() for l in text.splitlines() if l.strip()]
        return lines[:count] if lines else [text]
    return arr[:count]


def create_issue(title: str, body: str, labels=None):
    url = f"https://api.github.com/repos/{REPO}/issues"
    headers = {"Authorization": f"token {GITHUB_TOKEN}", "Accept": "application/vnd.github+json"}
    payload = {"title": title, "body": body, "labels": labels or []}
    r = requests.post(url, headers=headers, json=payload)
    if r.status_code not in (200, 201):
        print("Failed to create issue:", r.status_code, r.text)
        sys.exit(1)
    print("Created issue:", r.json().get("html_url"))
    return r.json()


def main():
    topic = os.getenv("AI_TOPIC", "Ideas for posts about Ro-app: features and community growth")
    variants = generate_variants(topic, count=int(os.getenv("AI_VARIANTS", "3")))
    now = datetime.utcnow().isoformat()
    title = f"AI Drafts: {topic} — {now[:19]}Z"
    body = "AI-generated draft post variants:\n\n"
    for i, v in enumerate(variants, start=1):
        body += f"{i}. {v}\n\n"
    body += "\n---\nGenerated by AI PoC. Edit before publishing.\n"
    create_issue(title, body, labels=ISSUE_LABELS)


if __name__ == "__main__":
    main()
