#!/usr/bin/env python3
import json
import os
from datetime import datetime, timezone

import requests
from dotenv import load_dotenv

load_dotenv()

OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
GITHUB_TOKEN = os.getenv("GH_PAT") or os.getenv("GITHUB_TOKEN")
REPO = os.getenv("GITHUB_REPOSITORY", "atalanrafael-jpg/MARSEL-Ro-app")
ISSUE_LABELS = ["ai/draft"]


def generate_variants(topic: str, count: int = 3):
    from openai import OpenAI

    client = OpenAI(api_key=OPENAI_API_KEY)
    prompt = (
        f'Generate {count} distinct short social media post variations about: "{topic}". '
        "Each variant should be a single paragraph, 1-2 sentences. Return only a JSON array of strings."
    )
    response = client.chat.completions.create(
        model=os.getenv("OPENAI_MODEL", "gpt-4o-mini"),
        messages=[{"role": "user", "content": prompt}],
        temperature=0.8,
        max_tokens=400,
    )
    text = (response.choices[0].message.content or "").strip()
    try:
        arr = json.loads(text)
        if isinstance(arr, list):
            return [str(item) for item in arr[:count]]
    except (json.JSONDecodeError, TypeError):
        pass
    lines = [line.strip() for line in text.splitlines() if line.strip()]
    return lines[:count] if lines else [text]


def create_issue(title: str, body: str, labels=None):
    url = f"https://api.github.com/repos/{REPO}/issues"
    headers = {
        "Authorization": f"Bearer {GITHUB_TOKEN}",
        "Accept": "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
    }
    payload = {"title": title, "body": body, "labels": labels or []}
    response = requests.post(url, headers=headers, json=payload, timeout=30)
    if response.status_code not in (200, 201):
        raise RuntimeError(f"Failed to create issue: {response.status_code} {response.text}")
    print("Created issue:", response.json().get("html_url"))


def main():
    if not OPENAI_API_KEY:
        print("OPENAI_API_KEY is not configured; generation skipped.")
        return 0
    if not GITHUB_TOKEN:
        raise RuntimeError("Missing GH_PAT or GITHUB_TOKEN")

    topic = os.getenv("AI_TOPIC", "Ideas for posts about MARSEL ROAPP: features and community growth")
    variants = generate_variants(topic, count=int(os.getenv("AI_VARIANTS", "3")))
    now = datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z")
    title = f"AI Drafts: {topic} — {now}"
    body = "AI-generated draft post variants:\n\n"
    body += "\n".join(f"{i}. {variant}" for i, variant in enumerate(variants, start=1))
    body += "\n\n---\nGenerated by AI PoC. Edit before publishing.\n"
    create_issue(title, body, labels=ISSUE_LABELS)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
